export interface I_Owner {
  _id: string;
  name: string;
  companyName: string;
  position: string;
  email: string;
  //linkdinLink:only required field
  linkdinLink: string;
  isEmailSent: boolean;
  isStared: boolean;
  isVmarked: boolean;
  tags: string[];
  imageSrc: string;
  comment: string;
  dateScraped: Date;
}

const data: I_Owner[] = [
  {
    _id: `1`,
    name: `moshe`,
    companyName: `company1`,
    position: `ceo`,
    email: `email1@mymail.com`,
    linkdinLink: `url1`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc1`,
    comment: `string1`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag2`, `tag3`],
  },
  {
    _id: `2`,
    name: `danny`,
    companyName: `company2`,
    position: `cto`,
    email: `email2@mymail.com`,
    linkdinLink: `url2`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc2`,
    comment: `string2`,
    dateScraped: new Date(),
    tags: [`tag4`, `tag5`, `tag6`],
  },
  {
    _id: `3`,
    name: `timmy`,
    companyName: `company3`,
    position: `ceo`,
    email: `email3@mymail.com`,
    linkdinLink: `url3`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc3`,
    comment: `string3`,
    dateScraped: new Date(),
    tags: [`tag3`, `tag4`, `tag5`],
  },
  {
    _id: `4`,
    name: `timmy`,
    companyName: `company4`,
    position: `cto`,
    email: `email4@mymail.com`,
    linkdinLink: `url4`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc4`,
    comment: `string4`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag2`, `tag3`],
  },
  {
    _id: `5`,
    name: `yossi`,
    companyName: `company5`,
    position: `ceo`,
    email: `email5@mymail.com`,
    linkdinLink: `url5`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc5`,
    comment: `string5`,
    dateScraped: new Date(),
    tags: [`tag2`, `tag3`, `tag4`],
  },
  {
    _id: `6`,
    name: `johney`,
    companyName: `company6`,
    position: `cto`,
    email: `email6@mymail.com`,
    linkdinLink: `url6`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc6`,
    comment: `string6`,
    dateScraped: new Date(),
    tags: [`tag3`, `tag4`, `tag5`],
  },
  {
    _id: `7`,
    name: `yaniv`,
    companyName: `company7`,
    position: `ceo`,
    email: `email7@mymail.com`,
    linkdinLink: `url7`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc7`,
    comment: `string7`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag6`, `tag7`],
  },
  {
    _id: `8`,
    name: `joey`,
    companyName: `company8`,
    position: `cto`,
    email: `email8@mymail.com`,
    linkdinLink: `url8`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc8`,
    comment: `string8`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag4`, `tag6`],
  },
  {
    _id: `9`,
    name: `avram`,
    companyName: `company9`,
    position: `ceo`,
    email: `email9@mymail.com`,
    linkdinLink: `url9`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc9`,
    comment: `string9`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag2`, `tag5`],
  },
  {
    _id: `10`,
    name: `yakov`,
    companyName: `company10`,
    position: `cto`,
    email: `email10@mymail.com`,
    linkdinLink: `url10`,
    isStared: false,
    isEmailSent: false,
    isVmarked: false,
    imageSrc: `imageSrc10`,
    comment: `string10`,
    dateScraped: new Date(),
    tags: [`tag1`, `tag3`, `tag5`],
  },
];
