[build]
    functions = "functions"
[[redirects]]
    from = "api/*"
    to = "https://linkedin-autobot-server.herokuapp.com/:splat 200"
    status = 200
    force = true

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*" 